### ISSUE TITLE
Diesen Bot können Rang geben? 

### ISSUE THREAD

**Issue by Hajatoby** [SuprexDE/TestBot#2]
Du können diese geben rechte geben rolle? 
waehre rischtig kuhl wenn du machen kannst diese.

**Comment by Aromastoffe** [comment]
Jaa, das auch seien kraaaaaaaassssssssssssssssssss!

**Comment by Steamarino** [comment]
:O

**Comment by JakobDerAllerechte** [comment]
:OO
